version: "3.2"

services:
  nginx:
    build: 
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8012:80"
    volumes:
      - .:/app/
    depends_on:
      - php
  
  php:
    image: "yiisoftware/yii2-php:7.4-fpm"
    volumes:
      - .:/app/
  